databases:
  - name: db
    databaseName: map_app_db
    user: postgres

services:
  - name: backend
    type: web
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py loaddata dumpdata.json
    startCommand: |
      python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: True
      - key: DB_NAME
        value: map_app_db
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: postgres

  - name: frontend
    type: web
    rootDir: frontend
    envVars:
      - key: API_URL
        value: http://localhost:8000
